/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param iso31661 The ISO 3166-1 alpha-2 country code of the administrative region.
 * @param country The full country name.
 * @param iso31662 The ISO 3166-2 code identifying the principal subdivision (ex: provinces or states) within a country.
 * @param state The full state or province name.
 */


data class Administrative (

    /* The ISO 3166-1 alpha-2 country code of the administrative region. */
    @SerializedName("iso_3166-1")
    val iso31661: kotlin.String? = null,

    /* The full country name. */
    @SerializedName("country")
    val country: kotlin.String? = null,

    /* The ISO 3166-2 code identifying the principal subdivision (ex: provinces or states) within a country. */
    @SerializedName("iso_3166-2")
    val iso31662: kotlin.String? = null,

    /* The full state or province name. */
    @SerializedName("state")
    val state: kotlin.String? = null

)

