/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param countryCode The [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country code.
 * @param countryText The country name
 * @param stateCode The abbreviation code for the state (varies by country).
 * @param stateText The state name.
 */


data class AdminRegion (

    /* The [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country code. */
    @SerializedName("country_code")
    val countryCode: kotlin.String? = null,

    /* The country name */
    @SerializedName("country_text")
    val countryText: kotlin.String? = null,

    /* The abbreviation code for the state (varies by country). */
    @SerializedName("state_code")
    val stateCode: kotlin.String? = null,

    /* The state name. */
    @SerializedName("state_text")
    val stateText: kotlin.String? = null

)

