/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param mountain 
 * @param local 
 * @param regional 
 * @param national 
 */


data class BikeNetwork (

    @SerializedName("mountain")
    val mountain: kotlin.Boolean? = null,

    @SerializedName("local")
    val local: kotlin.Boolean? = null,

    @SerializedName("regional")
    val regional: kotlin.Boolean? = null,

    @SerializedName("national")
    val national: kotlin.Boolean? = null

)

