/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.google.gson.annotations.SerializedName

/**
 * A rectangle in geographical coordinates from points at the southwest and northeast corners.
 *
 * @param northeast 
 * @param southwest 
 */


data class Bounds (

    @SerializedName("northeast")
    val northeast: LatLngLiteral,

    @SerializedName("southwest")
    val southwest: LatLngLiteral

)

