/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param time The time in minutes for the contour. Mutually exclusive of distance.
 * @param distance The distance in km for the contour. Mutually exclusive of time.
 * @param color The color for the output contour, specified as a hex value (without a leading `#`). If no color is specified, one will be assigned automatically.
 */


data class Contour (

    /* The time in minutes for the contour. Mutually exclusive of distance. */
    @SerializedName("time")
    val time: kotlin.Double? = null,

    /* The distance in km for the contour. Mutually exclusive of time. */
    @SerializedName("distance")
    val distance: kotlin.Double? = null,

    /* The color for the output contour, specified as a hex value (without a leading `#`). If no color is specified, one will be assigned automatically. */
    @SerializedName("color")
    val color: kotlin.String? = null

)

