/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param lat The latitude of a point in the shape.
 * @param lon The longitude of a point in the shape.
 */


data class Coordinate (

    /* The latitude of a point in the shape. */
    @SerializedName("lat")
    val lat: kotlin.Double,

    /* The longitude of a point in the shape. */
    @SerializedName("lon")
    val lon: kotlin.Double

)

