/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param auto 
 * @param bus 
 * @param taxi 
 * @param truck 
 * @param bicycle 
 * @param motorScooter 
 * @param motorcycle 
 * @param pedestrian 
 */


data class CostingOptions(

    @SerializedName("auto")
    val auto: AutoCostingOptions? = null,

    @SerializedName("bus")
    val bus: AutoCostingOptions? = null,

    @SerializedName("taxi")
    val taxi: AutoCostingOptions? = null,

    @SerializedName("truck")
    val truck: TruckCostingOptions? = null,

    @SerializedName("bicycle")
    val bicycle: BicycleCostingOptions? = null,

    @SerializedName("motor_scooter")
    val motorScooter: MotorScooterCostingOptions? = null,

    @SerializedName("motorcycle")
    val motorcycle: MotorcycleCostingOptions? = null,

    @SerializedName("pedestrian")
    val pedestrian: PedestrianCostingOptions? = null

)

