/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.example.mapapplication.originCode.net.models.DistanceUnit
import com.example.mapapplication.originCode.net.models.ValhallaLanguages
import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param units 
 * @param language 
 * @param directionsType The level of directional narrative to include. Locations and times will always be returned, but narrative generation verbosity can be controlled with this parameter.
 */


data class DirectionsOptions (

    @SerializedName("units")
    val units: DistanceUnit? = DistanceUnit.km,

    @SerializedName("language")
    val language: ValhallaLanguages? = ValhallaLanguages.enMinusUS,

    /* The level of directional narrative to include. Locations and times will always be returned, but narrative generation verbosity can be controlled with this parameter. */
    @SerializedName("directions_type")
    val directionsType: DirectionsType? = DirectionsType.instructions

) {

    /**
     * The level of directional narrative to include. Locations and times will always be returned, but narrative generation verbosity can be controlled with this parameter.
     *
     * Values: none,maneuvers,instructions
     */
    enum class DirectionsType(val value: kotlin.String) {
        @SerializedName(value = "none") none("none"),
        @SerializedName(value = "maneuvers") maneuvers("maneuvers"),
        @SerializedName(value = "instructions") instructions("instructions");
    }
}

