/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param exitNumber 
 * @param exitBranch 
 * @param exitToward 
 * @param exitName 
 */


data class EdgeSign (

    @SerializedName("exit_number")
    val exitNumber: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("exit_branch")
    val exitBranch: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("exit_toward")
    val exitToward: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("exit_name")
    val exitName: kotlin.collections.List<kotlin.String>? = null

)

