/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.example.mapapplication.originCode.net.models.IntersectingEdge
import com.example.mapapplication.originCode.net.models.NodeType
import com.google.gson.annotations.SerializedName

/**
 * The node at the end of this edge
 *
 * @param intersectingEdges A set of edges intersecting this node.
 * @param elapsedTime The elapsed time along the path to arrive at this node.
 * @param adminIndex The index into the `admins` list in which this node lies.
 * @param type 
 * @param fork True if this node is a fork.
 * @param timeZone The canonical TZDB identifier for the node's time zone.
 */


data class EndNode (

    /* A set of edges intersecting this node. */
    @SerializedName("intersecting_edges")
    val intersectingEdges: kotlin.collections.List<IntersectingEdge>? = null,

    /* The elapsed time along the path to arrive at this node. */
    @SerializedName("elapsed_time")
    val elapsedTime: kotlin.Double? = null,

    /* The index into the `admins` list in which this node lies. */
    @SerializedName("admin_index")
    val adminIndex: kotlin.Int? = null,

    @SerializedName("type")
    val type: NodeType? = null,

    /* True if this node is a fork. */
    @SerializedName("fork")
    val fork: kotlin.Boolean? = null,

    /* The canonical TZDB identifier for the node's time zone. */
    @SerializedName("time_zone")
    val timeZone: kotlin.String? = null

)

