/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param code This is the same as the HTTP status of the response.
 * @param message A short description of the error.
 * @param errors A list of errors which occurred. Each error contains an identifier for the type of error and a short description.
 * @param status A status code that indicates the error type.
 */


data class ErrorObject (

    /* This is the same as the HTTP status of the response. */
    @SerializedName("code")
    val code: java.math.BigDecimal,

    /* A short description of the error. */
    @SerializedName("message")
    val message: kotlin.String,

    /* A list of errors which occurred. Each error contains an identifier for the type of error and a short description. */
    @SerializedName("errors")
    val errors: kotlin.collections.List<ErrorDetail>,

    /* A status code that indicates the error type. */
    @SerializedName("status")
    val status: kotlin.String? = null

)

