/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models


import com.google.gson.annotations.SerializedName

/**
 * The total fare for the route.  ``` {   \"currency\" : \"USD\",   \"value\" : 6,   \"text\" : \"$6.00\" } ``` 
 *
 * @param currency An [ISO 4217 currency code](https://en.wikipedia.org/wiki/ISO_4217) indicating the currency that the amount is expressed in.
 * @param `value` The total fare amount, in the currency specified.
 * @param text The total fare amount, formatted in the requested language.
 */


data class Fare (

    /* An [ISO 4217 currency code](https://en.wikipedia.org/wiki/ISO_4217) indicating the currency that the amount is expressed in. */
    @SerializedName("currency")
    val currency: kotlin.String,

    /* The total fare amount, in the currency specified. */
    @SerializedName("value")
    val `value`: java.math.BigDecimal,

    /* The total fare amount, formatted in the requested language. */
    @SerializedName("text")
    val text: kotlin.String

)

