/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param curvature Curvature factor.
 * @param maxDownSlope The maximum downward slope. Uses 1 degree precision for slopes to -16 degrees, and 4 degree precision afterwards (up to a max of -76 degrees).
 * @param maxUpSlope The maximum upward slope. Uses 1 degree precision for slopes to 16 degrees, and 4 degree precision afterwards (up to a max of 76 degrees).
 * @param weightedGrade The weighted estimate of the grade.
 * @param length The length of the edge, in meters.
 */


data class GeoAttributes (

    /* Curvature factor. */
    @SerializedName("curvature")
    val curvature: kotlin.Int? = null,

    /* The maximum downward slope. Uses 1 degree precision for slopes to -16 degrees, and 4 degree precision afterwards (up to a max of -76 degrees). */
    @SerializedName("max_down_slope")
    val maxDownSlope: kotlin.Float? = null,

    /* The maximum upward slope. Uses 1 degree precision for slopes to 16 degrees, and 4 degree precision afterwards (up to a max of 76 degrees). */
    @SerializedName("max_up_slope")
    val maxUpSlope: kotlin.Float? = null,

    /* The weighted estimate of the grade. */
    @SerializedName("weighted_grade")
    val weightedGrade: kotlin.Float? = null,

    /* The length of the edge, in meters. */
    @SerializedName("length")
    val length: kotlin.Int? = null

)

