/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param type 
 */


data class GeoJSONGeometryBase (

    @SerializedName("type")
    val type: Type

) {

    /**
     * 
     *
     * Values: Point,MultiPoint,LineString,MultiLineString,Polygon,MultiPolygon
     */
    enum class Type(val value: kotlin.String) {
        @SerializedName(value = "Point") Point("Point"),
        @SerializedName(value = "MultiPoint") MultiPoint("MultiPoint"),
        @SerializedName(value = "LineString") LineString("LineString"),
        @SerializedName(value = "MultiLineString") MultiLineString("MultiLineString"),
        @SerializedName(value = "Polygon") Polygon("Polygon"),
        @SerializedName(value = "MultiPolygon") MultiPolygon("MultiPolygon");
    }
}

