/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param type 
 * @param coordinates 
 */


interface GeoJSONGeometry {

    @get:SerializedName("type")
    val type: Type
    @get:SerializedName("coordinates")
    val coordinates: kotlin.collections.List<kotlin.collections.List<kotlin.collections.List<kotlin.Double>>>
    /**
     * 
     *
     * Values: Point,MultiPoint,LineString,MultiLineString,Polygon,MultiPolygon
     */
    enum class Type(val value: kotlin.String) {
        @SerializedName(value = "Point") Point("Point"),
        @SerializedName(value = "MultiPoint") MultiPoint("MultiPoint"),
        @SerializedName(value = "LineString") LineString("LineString"),
        @SerializedName(value = "MultiLineString") MultiLineString("MultiLineString"),
        @SerializedName(value = "Polygon") Polygon("Polygon"),
        @SerializedName(value = "MultiPolygon") MultiPolygon("MultiPolygon");
    }
}

