/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.example.mapapplication.originCode.net.models.WiFiAccessPoint
import com.google.gson.annotations.SerializedName

/**
 * The request body must be formatted as JSON. The following fields are supported, and all fields are optional.
 *
 * @param homeMobileCountryCode The cell tower's Mobile Country Code (MCC).
 * @param homeMobileNetworkCode The cell tower's Mobile Network Code. This is the MNC for GSM and WCDMA; CDMA uses the System ID (SID).
 * @param radioType The mobile radio type. Supported values are lte, gsm, cdma, and wcdma. While this field is optional, it should be included if a value is available, for more accurate results.
 * @param carrier The carrier name.
 * @param considerIp Specifies whether to fall back to IP geolocation if wifi and cell tower signals are not available. Defaults to true. Set considerIp to false to disable fall back.
 * @param cellTowers The request body's cellTowers array contains zero or more cell tower objects.
 * @param wifiAccessPoints An array of two or more WiFi access point objects.
 */


data class GeolocationRequest (

    /* The cell tower's Mobile Country Code (MCC). */
    @SerializedName("homeMobileCountryCode")
    val homeMobileCountryCode: kotlin.Int? = null,

    /* The cell tower's Mobile Network Code. This is the MNC for GSM and WCDMA; CDMA uses the System ID (SID). */
    @SerializedName("homeMobileNetworkCode")
    val homeMobileNetworkCode: kotlin.Int? = null,

    /* The mobile radio type. Supported values are lte, gsm, cdma, and wcdma. While this field is optional, it should be included if a value is available, for more accurate results. */
    @SerializedName("radioType")
    val radioType: kotlin.String? = null,

    /* The carrier name. */
    @SerializedName("carrier")
    val carrier: kotlin.String? = null,

    /* Specifies whether to fall back to IP geolocation if wifi and cell tower signals are not available. Defaults to true. Set considerIp to false to disable fall back. */
    @SerializedName("considerIp")
    val considerIp: kotlin.String? = null,

    /* The request body's cellTowers array contains zero or more cell tower objects. */
    @SerializedName("cellTowers")
    val cellTowers: kotlin.collections.List<CellTower>? = null,

    /* An array of two or more WiFi access point objects. */
    @SerializedName("wifiAccessPoints")
    val wifiAccessPoints: kotlin.collections.List<WiFiAccessPoint>? = null

)

