/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.example.mapapplication.originCode.net.models.LatLngLiteral
import com.example.mapapplication.originCode.net.models.Bounds
import com.google.gson.annotations.SerializedName

/**
 * An object describing the location.
 *
 * @param location 
 * @param viewport 
 */


data class Geometry (

    @SerializedName("location")
    val location: LatLngLiteral,

    @SerializedName("viewport")
    val viewport: Bounds

)

