/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param version The current version of the service.
 * @param tilesetLastModified The UNIX timestamp when the tileset was last modified.
 * @param hasTiles Indicates whether a valid tileset is currently loaded.
 * @param hasAdmins Indicates whether the current tileset was built using the admin database.
 * @param hasTimezones Indicates whether the current tileset was built using the timezone database.
 * @param hasLiveTraffic Indicates whether live traffic tiles are currently available.
 * @param bbox GeoJSON representation of the tileset extent.
 * @param warnings Array containing warning objects.
 */


data class GetDirectionsStatus200Response (

    /* The current version of the service. */
    @SerializedName("version")
    val version: kotlin.String? = null,

    /* The UNIX timestamp when the tileset was last modified. */
    @SerializedName("tileset_last_modified")
    val tilesetLastModified: kotlin.Long? = null,

    /* Indicates whether a valid tileset is currently loaded. */
    @SerializedName("has_tiles")
    val hasTiles: kotlin.Boolean? = null,

    /* Indicates whether the current tileset was built using the admin database. */
    @SerializedName("has_admins")
    val hasAdmins: kotlin.Boolean? = null,

    /* Indicates whether the current tileset was built using the timezone database. */
    @SerializedName("has_timezones")
    val hasTimezones: kotlin.Boolean? = null,

    /* Indicates whether live traffic tiles are currently available. */
    @SerializedName("has_live_traffic")
    val hasLiveTraffic: kotlin.Boolean? = null,

    /* GeoJSON representation of the tileset extent. */
    @SerializedName("bbox")
    val bbox: kotlin.Any? = null,

    /* Array containing warning objects. */
    @SerializedName("warnings")
    val warnings: kotlin.collections.List<kotlin.String>? = null

)

