/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.example.mapapplication.originCode.net.models.GoogGeocodingResult
import com.example.mapapplication.originCode.net.models.GoogGeocodingStatus
import com.example.mapapplication.originCode.net.models.PlusCode
import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param results 
 * @param status 
 * @param plusCode 
 * @param errorMessage A short description of the error.
 */


data class GoogGeocodingResponse (

    @SerializedName("results")
    val results: kotlin.collections.List<GoogGeocodingResult>,

    @SerializedName("status")
    val status: GoogGeocodingStatus,

    @SerializedName("plus_code")
    val plusCode: PlusCode? = null,

    /* A short description of the error. */
    @SerializedName("error_message")
    val errorMessage: kotlin.String? = null

)

