/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.example.mapapplication.originCode.net.models.Place
import com.example.mapapplication.originCode.net.models.PlacesDetailsStatus
import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param htmlAttributions May contain a set of attributions about this listing which must be displayed to the user (some listings may not have attribution).
 * @param result 
 * @param status 
 * @param infoMessages When the service returns additional information about the request specification, there may be an additional `info_messages` field within the response object. This field is only returned for successful requests. It may not always be returned, and its content is subject to change. 
 */


data class GoogPlacesDetailsResponse (

    /* May contain a set of attributions about this listing which must be displayed to the user (some listings may not have attribution). */
    @SerializedName("html_attributions")
    val htmlAttributions: kotlin.collections.List<kotlin.String>,

    @SerializedName("result")
    val result: Place,

    @SerializedName("status")
    val status: PlacesDetailsStatus,

    /* When the service returns additional information about the request specification, there may be an additional `info_messages` field within the response object. This field is only returned for successful requests. It may not always be returned, and its content is subject to change.  */
    @SerializedName("info_messages")
    val infoMessages: kotlin.collections.List<kotlin.String>? = null

)

