/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.example.mapapplication.originCode.net.models.Place
import com.example.mapapplication.originCode.net.models.PlacesSearchStatus
import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param htmlAttributions May contain a set of attributions about this listing which must be displayed to the user (some listings may not have attribution).
 * @param results Contains an array of places. <div class=\"caution\">Place Search requests return a subset of the fields that are returned by Place Details requests. If the field you want is not returned by Place Search, you can use Place Search to get a `place_id`, then use that Place ID to make a Place Details request.</div> 
 * @param status 
 * @param errorMessage When the service returns a status code other than `OK<`, there may be an additional `error_message` field within the response object. This field contains more detailed information about thereasons behind the given status code. This field is not always returned, and its content is subject to change. 
 * @param infoMessages When the service returns additional information about the request specification, there may be an additional `info_messages` field within the response object. This field is only returned for successful requests. It may not always be returned, and its content is subject to change. 
 * @param nextPageToken Contains a token that can be used to return up to 20 additional results. A next_page_token will not be returned if there are no additional results to display. The maximum number of results that can be returned is 60. There is a short delay between when a next_page_token is issued, and when it will become valid. 
 */


data class GoogPlacesNearbySearchResponse (

    /* May contain a set of attributions about this listing which must be displayed to the user (some listings may not have attribution). */
    @SerializedName("html_attributions")
    val htmlAttributions: kotlin.collections.List<kotlin.String>,

    /* Contains an array of places. <div class=\"caution\">Place Search requests return a subset of the fields that are returned by Place Details requests. If the field you want is not returned by Place Search, you can use Place Search to get a `place_id`, then use that Place ID to make a Place Details request.</div>  */
    @SerializedName("results")
    val results: kotlin.collections.List<Place>,

    @SerializedName("status")
    val status: PlacesSearchStatus,

    /* When the service returns a status code other than `OK<`, there may be an additional `error_message` field within the response object. This field contains more detailed information about thereasons behind the given status code. This field is not always returned, and its content is subject to change.  */
    @SerializedName("error_message")
    val errorMessage: kotlin.String? = null,

    /* When the service returns additional information about the request specification, there may be an additional `info_messages` field within the response object. This field is only returned for successful requests. It may not always be returned, and its content is subject to change.  */
    @SerializedName("info_messages")
    val infoMessages: kotlin.collections.List<kotlin.String>? = null,

    /* Contains a token that can be used to return up to 20 additional results. A next_page_token will not be returned if there are no additional results to display. The maximum number of results that can be returned is 60. There is a short delay between when a next_page_token is issued, and when it will become valid.  */
    @SerializedName("next_page_token")
    val nextPageToken: kotlin.String? = null

)

