/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.example.mapapplication.originCode.net.models.LatLngLiteral
import com.google.gson.annotations.SerializedName

/**
 * An object describing the location.
 *
 * @param location 
 * @param locationType Stores additional data about the specified location. The following values are currently supported:  - \"ROOFTOP\" indicates that the returned result is a precise geocode for which we have location information accurate down to street address precision. - \"RANGE_INTERPOLATED\" indicates that the returned result reflects an approximation (usually on a road) interpolated between two precise points (such as intersections). Interpolated results are generally returned when rooftop geocodes are unavailable for a street address. - \"GEOMETRIC_CENTER\" indicates that the returned result is the geometric center of a result such as a polyline (for example, a street) or polygon (region). - \"APPROXIMATE\" indicates that the returned result is approximate. 
 * @param viewport 
 * @param bounds 
 */


data class GoogGeocodingGeometry (

    @SerializedName("location")
    val location: LatLngLiteral,

    /* Stores additional data about the specified location. The following values are currently supported:  - \"ROOFTOP\" indicates that the returned result is a precise geocode for which we have location information accurate down to street address precision. - \"RANGE_INTERPOLATED\" indicates that the returned result reflects an approximation (usually on a road) interpolated between two precise points (such as intersections). Interpolated results are generally returned when rooftop geocodes are unavailable for a street address. - \"GEOMETRIC_CENTER\" indicates that the returned result is the geometric center of a result such as a polyline (for example, a street) or polygon (region). - \"APPROXIMATE\" indicates that the returned result is approximate.  */
    @SerializedName("location_type")
    val locationType: LocationType,

    @SerializedName("viewport")
    val viewport: Bounds,

    @SerializedName("bounds")
    val bounds: Bounds? = null

) {

    /**
     * Stores additional data about the specified location. The following values are currently supported:  - \"ROOFTOP\" indicates that the returned result is a precise geocode for which we have location information accurate down to street address precision. - \"RANGE_INTERPOLATED\" indicates that the returned result reflects an approximation (usually on a road) interpolated between two precise points (such as intersections). Interpolated results are generally returned when rooftop geocodes are unavailable for a street address. - \"GEOMETRIC_CENTER\" indicates that the returned result is the geometric center of a result such as a polyline (for example, a street) or polygon (region). - \"APPROXIMATE\" indicates that the returned result is approximate. 
     *
     * Values: ROOFTOP,RANGE_INTERPOLATED,GEOMETRIC_CENTER,APPROXIMATE
     */
    enum class LocationType(val value: kotlin.String) {
        @SerializedName(value = "ROOFTOP") ROOFTOP("ROOFTOP"),
        @SerializedName(value = "RANGE_INTERPOLATED") RANGE_INTERPOLATED("RANGE_INTERPOLATED"),
        @SerializedName(value = "GEOMETRIC_CENTER") GEOMETRIC_CENTER("GEOMETRIC_CENTER"),
        @SerializedName(value = "APPROXIMATE") APPROXIMATE("APPROXIMATE");
    }
}

