/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.example.mapapplication.originCode.net.models.IsochroneProperties
import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param properties 
 * @param geometry 
 * @param type 
 */


data class IsochroneFeature (

    @SerializedName("properties")
    val properties: IsochroneProperties? = null,

    @SerializedName("geometry")
    val geometry: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @SerializedName("type")
    val type: Type? = null

) {

    /**
     * 
     *
     * Values: Feature
     */
    enum class Type(val value: kotlin.String) {
        @SerializedName(value = "Feature") Feature("Feature");
    }
}

