/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.google.gson.annotations.SerializedName
import com.mapbox.geojson.Feature

/**
 * 
 *
 * @param features 
 * @param type 
 * @param id 
 */


data class IsochroneResponse (

    @SerializedName("features")
    val features: kotlin.collections.List<IsochroneFeature>,//List<Feature>,

    @SerializedName("type")
    val type: Type,

    @SerializedName("id")
    val id: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: FeatureCollection
     */
    enum class Type(val value: kotlin.String) {
        @SerializedName(value = "FeatureCollection") FeatureCollection("FeatureCollection");
    }
}

