/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param fillColor 
 * @param opacity 
 * @param fill 
 * @param fillOpacity 
 * @param color 
 * @param contour 
 * @param metric 
 */


data class IsochroneProperties (

    @SerializedName("fillColor")
    val fillColor: kotlin.String? = null,

    @SerializedName("opacity")
    val opacity: kotlin.Float? = null,

    @SerializedName("fill")
    val fill: kotlin.String? = null,

    @SerializedName("fillOpacity")
    val fillOpacity: kotlin.Float? = null,

    @SerializedName("color")
    val color: kotlin.String? = null,

    @SerializedName("contour")
    val contour: kotlin.Float? = null,

    @SerializedName("metric")
    val metric: Metric? = null

) {

    /**
     * 
     *
     * Values: time,distance
     */
    enum class Metric(val value: kotlin.String) {
        @SerializedName(value = "time") time("time"),
        @SerializedName(value = "distance") distance("distance");
    }
}

