/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models


import com.google.gson.annotations.SerializedName

/**
 * An object describing a specific location with Latitude and Longitude in decimal degrees.
 *
 * @param latitude Latitude in decimal degrees
 * @param longitude Longitude in decimal degrees
 */


data class LatitudeLongitudeLiteral (

    /* Latitude in decimal degrees */
    @SerializedName("latitude")
    val latitude: java.math.BigDecimal,

    /* Longitude in decimal degrees */
    @SerializedName("longitude")
    val longitude: java.math.BigDecimal

)

