/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models


import com.google.gson.annotations.SerializedName

/**
 * An object describing a specific location with Latitude and Longitude in decimal degrees.
 *
 * @param lat Latitude in decimal degrees
 * @param lng Longitude in decimal degrees
 */


data class LatLngLiteral (

    /* Latitude in decimal degrees */
    @SerializedName("lat")
    val lat: java.math.BigDecimal,

    /* Longitude in decimal degrees */
    @SerializedName("lng")
    val lng: java.math.BigDecimal

)

