/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.example.mapapplication.originCode.net.models.NodeId
import com.example.mapapplication.originCode.net.models.NodeType
import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param lat The latitude of a point in the shape.
 * @param lon The longitude of a point in the shape.
 * @param trafficSignal 
 * @param type 
 * @param nodeId 
 * @param access 
 * @param edgeCount 
 * @param administrative 
 * @param intersectionType 
 * @param density 
 * @param localEdgeCount 
 * @param modeChange 
 */


data class LocateNode (

    /* The latitude of a point in the shape. */
    @SerializedName("lat")
    val lat: kotlin.Double,

    /* The longitude of a point in the shape. */
    @SerializedName("lon")
    val lon: kotlin.Double,

    @SerializedName("traffic_signal")
    val trafficSignal: kotlin.Boolean? = null,

    @SerializedName("type")
    val type: NodeType? = null,

    @SerializedName("node_id")
    val nodeId: NodeId? = null,

    @SerializedName("access")
    val access: Access? = null,

    @SerializedName("edge_count")
    val edgeCount: kotlin.Int? = null,

    @SerializedName("administrative")
    val administrative: Administrative? = null,

    @SerializedName("intersection_type")
    val intersectionType: IntersectionType? = null,

    @SerializedName("density")
    val density: kotlin.Int? = null,

    @SerializedName("local_edge_count")
    val localEdgeCount: kotlin.Int? = null,

    @SerializedName("mode_change")
    val modeChange: kotlin.Boolean? = null

) {

    /**
     * 
     *
     * Values: regular,`false`,deadMinusEnd,fork
     */
    enum class IntersectionType(val value: kotlin.String) {
        @SerializedName(value = "regular") regular("regular"),
        @SerializedName(value = "false") `false`("false"),
        @SerializedName(value = "dead-end") deadMinusEnd("dead-end"),
        @SerializedName(value = "fork") fork("fork");
    }
}

