/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.example.mapapplication.originCode.net.models.BikeNetwork
import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param meanElevation The mean elevation, in meters, relative to sea level.
 * @param shape An encoded polyline (https://developers.google.com/maps/documentation/utilities/polylinealgorithm). Note that the polyline is always encoded with 6 digits of precision, whereas most implementations default to 5.
 * @param names A list of names that the edge goes by.
 * @param bikeNetwork 
 * @param wayId 
 */


data class LocateEdgeInfo (

    /* The mean elevation, in meters, relative to sea level. */
    @SerializedName("mean_elevation")
    val meanElevation: kotlin.Float? = null,

    /* An encoded polyline (https://developers.google.com/maps/documentation/utilities/polylinealgorithm). Note that the polyline is always encoded with 6 digits of precision, whereas most implementations default to 5. */
    @SerializedName("shape")
    val shape: kotlin.String? = null,

    /* A list of names that the edge goes by. */
    @SerializedName("names")
    val names: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("bike_network")
    val bikeNetwork: BikeNetwork? = null,

    @SerializedName("way_id")
    val wayId: kotlin.Int? = null

)

