/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id An identifier to disambiguate requests (echoed by the server).
 * @param inputLat The input (searched) latitude.
 * @param inputLon The input (searched) longitude.
 * @param nodes 
 * @param edges 
 */


data class LocateObject (

    /* An identifier to disambiguate requests (echoed by the server). */
    @SerializedName("id")
    val id: kotlin.String? = null,

    /* The input (searched) latitude. */
    @SerializedName("input_lat")
    val inputLat: kotlin.Double? = null,

    /* The input (searched) longitude. */
    @SerializedName("input_lon")
    val inputLon: kotlin.Double? = null,

    @SerializedName("nodes")
    val nodes: kotlin.collections.List<LocateNode>? = null,

    @SerializedName("edges")
    val edges: kotlin.collections.List<LocateEdge>? = null

)

