/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.example.mapapplication.originCode.net.models.LocateEdgeInfo
import com.example.mapapplication.originCode.net.models.NodeId
import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param edgeId 
 * @param correlatedLat 
 * @param correlatedLon 
 * @param percentAlong 
 * @param sideOfStreet 
 * @param linearReference A base64-encoded [OpenLR location reference](https://www.openlr-association.com/fileadmin/user_upload/openlr-whitepaper_v1.5.pdf), for a graph edge of the road network matched by the query.
 * @param outboundReach 
 * @param heading 
 * @param inboundReach 
 * @param distance 
 * @param predictedSpeeds Predicted speed information based on historical data. If available, this will include 2016 entries. Each entry represents 5 minutes, where the first entry represents midnight on Monday, the second entry represents 00:05 on Monday, etc.
 * @param edgeInfo 
 * @param edge 
 * @param warnings 
 */


data class LocateEdge (

    @SerializedName("edge_id")
    val edgeId: NodeId? = null,

    @SerializedName("correlated_lat")
    val correlatedLat: kotlin.Double? = null,

    @SerializedName("correlated_lon")
    val correlatedLon: kotlin.Double? = null,

    @SerializedName("percent_along")
    val percentAlong: kotlin.Double? = null,

    @SerializedName("side_of_street")
    val sideOfStreet: SideOfStreet? = null,

    /* A base64-encoded [OpenLR location reference](https://www.openlr-association.com/fileadmin/user_upload/openlr-whitepaper_v1.5.pdf), for a graph edge of the road network matched by the query. */
    @SerializedName("linear_reference")
    val linearReference: kotlin.String? = null,

    @SerializedName("outbound_reach")
    val outboundReach: kotlin.Int? = null,

    @SerializedName("heading")
    val heading: kotlin.Float? = null,

    @SerializedName("inbound_reach")
    val inboundReach: kotlin.Int? = null,

    @SerializedName("distance")
    val distance: kotlin.Float? = null,

    /* Predicted speed information based on historical data. If available, this will include 2016 entries. Each entry represents 5 minutes, where the first entry represents midnight on Monday, the second entry represents 00:05 on Monday, etc. */
    @SerializedName("predicted_speeds")
    val predictedSpeeds: kotlin.collections.List<kotlin.Int>? = null,

    @SerializedName("edge_info")
    val edgeInfo: LocateEdgeInfo? = null,

    @SerializedName("edge")
    val edge: LocateDetailedEdge? = null,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<kotlin.String>? = null

) {

    /**
     * 
     *
     * Values: left,right,neither
     */
    enum class SideOfStreet(val value: kotlin.String) {
        @SerializedName(value = "left") left("left"),
        @SerializedName(value = "right") right("right"),
        @SerializedName(value = "neither") neither("neither");
    }
}

