/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param text The interchange sign text (varies based on the context; see the `maneuverSign` schema).
 * @param isRouteNumber True if the sign is a route number.
 * @param consecutiveCount The frequency of this sign element within a set a consecutive signs.
 */


data class ManeuverSignElement (

    /* The interchange sign text (varies based on the context; see the `maneuverSign` schema). */
    @SerializedName("text")
    val text: kotlin.String,

    /* True if the sign is a route number. */
    @SerializedName("is_route_number")
    val isRouteNumber: kotlin.Boolean? = null,

    /* The frequency of this sign element within a set a consecutive signs. */
    @SerializedName("consecutive_count")
    val consecutiveCount: kotlin.Int? = null

)

