/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.example.mapapplication.originCode.net.models.ManeuverSignElement
import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param exitNumberElements A list of exit number elements. This is typically just a single value.
 * @param exitBranchElements A list of exit branch elements. The text is a subsequent road name or route number after the sign.
 * @param exitTowardElements A list of exit name elements. The text is the interchange identifier (used more frequently outside the US).
 * @param exitNameElements A list of exit name elements. The text is the location where the road ahead goes (typically a city, but occasionally a road name or route number).
 */


data class ManeuverSign (

    /* A list of exit number elements. This is typically just a single value. */
    @SerializedName("exit_number_elements")
    val exitNumberElements: kotlin.collections.List<ManeuverSignElement>? = null,

    /* A list of exit branch elements. The text is a subsequent road name or route number after the sign. */
    @SerializedName("exit_branch_elements")
    val exitBranchElements: kotlin.collections.List<ManeuverSignElement>? = null,

    /* A list of exit name elements. The text is the interchange identifier (used more frequently outside the US). */
    @SerializedName("exit_toward_elements")
    val exitTowardElements: kotlin.collections.List<ManeuverSignElement>? = null,

    /* A list of exit name elements. The text is the location where the road ahead goes (typically a city, but occasionally a road name or route number). */
    @SerializedName("exit_name_elements")
    val exitNameElements: kotlin.collections.List<ManeuverSignElement>? = null

)

