/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param sources The list of starting locations
 * @param targets The list of ending locations
 * @param costing 
 * @param id An identifier to disambiguate requests (echoed by the server).
 * @param costingOptions 
 * @param matrixLocations Only applicable to one-to-many or many-to-one requests. This defaults to all locations. When specified explicitly, this option allows a partial result to be returned. This is basically equivalent to \"find the closest/best locations out of the full set.\" This can have a dramatic improvement for large requests.
 * @param directionsOptions 
 */


data class MatrixRequest (

    /* The list of starting locations */
    @SerializedName("sources")
    val sources: kotlin.collections.List<Coordinate>,

    /* The list of ending locations */
    @SerializedName("targets")
    val targets: kotlin.collections.List<Coordinate>,

    @SerializedName("costing")
    val costing: MatrixCostingModel,

    /* An identifier to disambiguate requests (echoed by the server). */
    @SerializedName("id")
    val id: kotlin.String = "matrix",

    @SerializedName("costing_options")
    val costingOptions: CostingOptions? = null,

    /* Only applicable to one-to-many or many-to-one requests. This defaults to all locations. When specified explicitly, this option allows a partial result to be returned. This is basically equivalent to \"find the closest/best locations out of the full set.\" This can have a dramatic improvement for large requests. */
    @SerializedName("matrix_locations")
    val matrixLocations: kotlin.Int? = null,

    @SerializedName("directions_options")
    val directionsOptions: DirectionsOptions? = null

)

