/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param locations 
 * @param costing 
 * @param costingOptions 
 * @param verbose 
 * @param directionsOptions 
 */


data class NearestRoadsRequest (

    @SerializedName("locations")
    val locations: kotlin.collections.List<Coordinate>,

    @SerializedName("costing")
    val costing: CostingModel? = null,

    @SerializedName("costing_options")
    val costingOptions: CostingOptions? = null,

    @SerializedName("verbose")
    val verbose: kotlin.Boolean? = false,

    @SerializedName("directions_options")
    val directionsOptions: DirectionsOptions? = null

)

