/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param code This is the same as the HTTP status of the response.
 * @param message A short description of the error.
 * @param status An error such as `INVALID_ARGUMENT`.
 */


data class NearestRoadsError (

    /* This is the same as the HTTP status of the response. */
    @SerializedName("code")
    val code: java.math.BigDecimal,

    /* A short description of the error. */
    @SerializedName("message")
    val message: kotlin.String,

    /* An error such as `INVALID_ARGUMENT`. */
    @SerializedName("status")
    val status: kotlin.String

)

