/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param snappedPoints An array of snapped points.
 */


data class NearestRoadsResponse (

    /* An array of snapped points. */
    @SerializedName("snappedPoints")
    val snappedPoints: kotlin.collections.List<kotlin.String>? = null

)

