/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param `value` 
 * @param tileId 
 * @param level 
 */


data class NodeId (

    @SerializedName("id")
    val id: kotlin.Long? = null,

    @SerializedName("value")
    val `value`: kotlin.Long? = null,

    @SerializedName("tile_id")
    val tileId: kotlin.Long? = null,

    @SerializedName("level")
    val level: kotlin.Int? = null

)

