/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param locations The list of locations. The first and last are assumed to be the start and end points, and all intermediate points are locations that you want to visit along the way.
 * @param costing 
 * @param id An identifier to disambiguate requests (echoed by the server).
 * @param costingOptions 
 * @param directionsOptions 
 */


data class OptimizedRouteRequest (

    /* The list of locations. The first and last are assumed to be the start and end points, and all intermediate points are locations that you want to visit along the way. */
    @SerializedName("locations")
    val locations: kotlin.collections.List<Coordinate>,

    @SerializedName("costing")
    val costing: MatrixCostingModel,

    /* An identifier to disambiguate requests (echoed by the server). */
    @SerializedName("id")
    val id: kotlin.String? = null,

    @SerializedName("costing_options")
    val costingOptions: CostingOptions? = null,

    @SerializedName("directions_options")
    val directionsOptions: DirectionsOptions? = null

)

