/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param geocoding 
 * @param features 
 * @param bbox An array of 4 floating point numbers representing the (W, S, E, N) extremes of the features found.
 */


data class PeliasResponse (

    @SerializedName("geocoding")
    val geocoding: GeocodingObject,

    @SerializedName("features")
    val features: kotlin.collections.List<PeliasGeoJSONFeature>,

    /* An array of 4 floating point numbers representing the (W, S, E, N) extremes of the features found. */
    @SerializedName("bbox")
    val bbox: kotlin.collections.List<kotlin.Double>? = null

)

