/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.google.gson.annotations.SerializedName

/**
 * Optional additional information from the underlying data source (ex: OSM). This includes select fields. The most useful fields are mapped in the definition here, but others may be available.
 *
 * @param osm 
 */


data class PeliasGeoJSONPropertiesAddendum (

    @SerializedName("osm")
    val osm: PeliasGeoJSONPropertiesAddendumOsm? = null

) : kotlin.collections.HashMap<String, kotlin.Any>()

