/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models


import com.google.gson.annotations.SerializedName

/**
 * Our database contains info from multiple sources. These identifiers can be used to either limit search results or to determine the relevance of a result.
 *
 * Values: openstreetmap,openaddresses,whosonfirst,geonames
 */

enum class PeliasSource(val value: kotlin.String) {

    @SerializedName(value = "openstreetmap")
    openstreetmap("openstreetmap"),

    @SerializedName(value = "openaddresses")
    openaddresses("openaddresses"),

    @SerializedName(value = "whosonfirst")
    whosonfirst("whosonfirst"),

    @SerializedName(value = "geonames")
    geonames("geonames");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PeliasSource) "$data" else null

        /**
         * Returns a valid [PeliasSource] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PeliasSource? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

