/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.example.mapapplication.originCode.net.models.PeliasGeoJSONProperties
import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param type 
 * @param geometry 
 * @param properties 
 * @param bbox An array of 4 floating point numbers representing the (W, S, E, N) extremes of the features found.
 * @param id 
 */


data class PeliasGeoJSONFeature (

    @SerializedName("type")
    val type: Type,

    @SerializedName("geometry")
    val geometry: GeoJSONPoint,

    @SerializedName("properties")
    val properties: PeliasGeoJSONProperties? = null,

    /* An array of 4 floating point numbers representing the (W, S, E, N) extremes of the features found. */
    @SerializedName("bbox")
    val bbox: kotlin.collections.List<kotlin.Double>? = null,

    @SerializedName("id")
    val id: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: Feature
     */
    enum class Type(val value: kotlin.String) {
        @SerializedName(value = "Feature") Feature("Feature");
    }
}

