/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models


import com.google.gson.annotations.SerializedName

/**
 * A review of the place submitted by a user.
 *
 * @param authorName The name of the user who submitted the review. Anonymous reviews are attributed to \"A Origins user\".
 * @param rating The user's overall rating for this place. This is a whole number, ranging from 1 to 5.
 * @param relativeTimeDescription The time that the review was submitted in text, relative to the current time.
 * @param time The time that the review was submitted, measured in the number of seconds since since midnight, January 1, 1970 UTC.
 * @param authorUrl The URL to the user's Origins Maps Local Guides profile, if available.
 * @param profilePhotoUrl The URL to the user's profile photo, if available.
 * @param language An IETF language code indicating the language used in the user's review. This field contains the main language tag only, and not the secondary tag indicating country or region. For example, all the English reviews are tagged as 'en', and not 'en-AU' or 'en-UK' and so on.
 * @param text The user's review. When reviewing a location with Origins Places, text reviews are considered optional. Therefore, this field may be empty. Note that this field may include simple HTML markup. For example, the entity reference `&amp;` may represent an ampersand character.
 */


data class PlaceReview (

    /* The name of the user who submitted the review. Anonymous reviews are attributed to \"A Origins user\". */
    @SerializedName("author_name")
    val authorName: kotlin.String,

    /* The user's overall rating for this place. This is a whole number, ranging from 1 to 5. */
    @SerializedName("rating")
    val rating: java.math.BigDecimal,

    /* The time that the review was submitted in text, relative to the current time. */
    @SerializedName("relative_time_description")
    val relativeTimeDescription: kotlin.String,

    /* The time that the review was submitted, measured in the number of seconds since since midnight, January 1, 1970 UTC. */
    @SerializedName("time")
    val time: java.math.BigDecimal,

    /* The URL to the user's Origins Maps Local Guides profile, if available. */
    @SerializedName("author_url")
    val authorUrl: kotlin.String? = null,

    /* The URL to the user's profile photo, if available. */
    @SerializedName("profile_photo_url")
    val profilePhotoUrl: kotlin.String? = null,

    /* An IETF language code indicating the language used in the user's review. This field contains the main language tag only, and not the secondary tag indicating country or region. For example, all the English reviews are tagged as 'en', and not 'en-AU' or 'en-UK' and so on. */
    @SerializedName("language")
    val language: kotlin.String? = null,

    /* The user's review. When reviewing a location with Origins Places, text reviews are considered optional. Therefore, this field may be empty. Note that this field may include simple HTML markup. For example, the entity reference `&amp;` may represent an ampersand character. */
    @SerializedName("text")
    val text: kotlin.String? = null

)

