/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param predictions Contains an array of predictions. 
 * @param status 
 * @param errorMessage When the service returns a status code other than `OK`, there may be an additional `error_message` field within the response object. This field contains more detailed information about thereasons behind the given status code. This field is not always returned, and its content is subject to change. 
 * @param infoMessages When the service returns additional information about the request specification, there may be an additional `info_messages` field within the response object. This field is only returned for successful requests. It may not always be returned, and its content is subject to change. 
 */


data class PlacesQueryAutocompleteResponse (

    /* Contains an array of predictions.  */
    @SerializedName("predictions")
    val predictions: kotlin.collections.List<PlaceAutocompletePrediction>,

    @SerializedName("status")
    val status: PlacesAutocompleteStatus,

    /* When the service returns a status code other than `OK`, there may be an additional `error_message` field within the response object. This field contains more detailed information about thereasons behind the given status code. This field is not always returned, and its content is subject to change.  */
    @SerializedName("error_message")
    val errorMessage: kotlin.String? = null,

    /* When the service returns additional information about the request specification, there may be an additional `info_messages` field within the response object. This field is only returned for successful requests. It may not always be returned, and its content is subject to change.  */
    @SerializedName("info_messages")
    val infoMessages: kotlin.collections.List<kotlin.String>? = null

)

