/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param `open` 
 * @param close 
 */


data class PlaceOpeningHoursPeriod (

    @SerializedName("open")
    val `open`: PlaceOpeningHoursPeriodDetail,

    @SerializedName("close")
    val close: PlaceOpeningHoursPeriodDetail

)

