/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param length Length of the matched substring in the prediction result text.
 * @param offset Start location of the matched substring in the prediction result text.
 */


data class PlaceAutocompleteMatchedSubstring (

    /* Length of the matched substring in the prediction result text. */
    @SerializedName("length")
    val length: java.math.BigDecimal,

    /* Start location of the matched substring in the prediction result text. */
    @SerializedName("offset")
    val offset: java.math.BigDecimal

)

