/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.google.gson.annotations.SerializedName

/**
 * An object describing the opening hours of a place.
 *
 * @param openNow A boolean value indicating if the place is open at the current time.
 * @param periods An array of opening periods covering seven days, starting from Sunday, in chronological order. 
 * @param weekdayText An array of strings describing in human-readable text the hours of the place.
 */


data class PlaceOpeningHours (

    /* A boolean value indicating if the place is open at the current time. */
    @SerializedName("open_now")
    val openNow: kotlin.Boolean? = null,

    /* An array of opening periods covering seven days, starting from Sunday, in chronological order.  */
    @SerializedName("periods")
    val periods: kotlin.collections.List<PlaceOpeningHoursPeriod>? = null,

    /* An array of strings describing in human-readable text the hours of the place. */
    @SerializedName("weekday_text")
    val weekdayText: kotlin.collections.List<kotlin.String>? = null

)

