/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param mainText Contains the main text of a prediction, usually the name of the place.
 * @param mainTextMatchedSubstrings Contains an array with `offset` value and `length`. These describe the location of the entered term in the prediction result text, so that the term can be highlighted if desired.
 * @param secondaryText Contains the secondary text of a prediction, usually the location of the place.
 * @param secondaryTextMatchedSubstrings Contains an array with `offset` value and `length`. These describe the location of the entered term in the prediction result text, so that the term can be highlighted if desired.
 */


data class PlaceAutocompleteStructuredFormat (

    /* Contains the main text of a prediction, usually the name of the place. */
    @SerializedName("main_text")
    val mainText: kotlin.String,

    /* Contains an array with `offset` value and `length`. These describe the location of the entered term in the prediction result text, so that the term can be highlighted if desired. */
    @SerializedName("main_text_matched_substrings")
    val mainTextMatchedSubstrings: kotlin.collections.List<PlaceAutocompleteMatchedSubstring>,

    /* Contains the secondary text of a prediction, usually the location of the place. */
    @SerializedName("secondary_text")
    val secondaryText: kotlin.String,

    /* Contains an array with `offset` value and `length`. These describe the location of the entered term in the prediction result text, so that the term can be highlighted if desired. */
    @SerializedName("secondary_text_matched_substrings")
    val secondaryTextMatchedSubstrings: kotlin.collections.List<PlaceAutocompleteMatchedSubstring>? = null

)

