/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param golfCart 
 * @param truck 
 * @param pedestrian 
 * @param wheelchair 
 * @param taxi 
 * @param HOV 
 * @param emergency 
 * @param motorcycle 
 * @param car 
 * @param moped 
 * @param bus 
 * @param bicycle 
 */


data class Restrictions (

    @SerializedName("golf_cart")
    val golfCart: kotlin.Boolean? = null,

    @SerializedName("truck")
    val truck: kotlin.Boolean? = null,

    @SerializedName("pedestrian")
    val pedestrian: kotlin.Boolean? = null,

    @SerializedName("wheelchair")
    val wheelchair: kotlin.Boolean? = null,

    @SerializedName("taxi")
    val taxi: kotlin.Boolean? = null,

    @SerializedName("HOV")
    val HOV: kotlin.Boolean? = null,

    @SerializedName("emergency")
    val emergency: kotlin.Boolean? = null,

    @SerializedName("motorcycle")
    val motorcycle: kotlin.Boolean? = null,

    @SerializedName("car")
    val car: kotlin.Boolean? = null,

    @SerializedName("moped")
    val moped: kotlin.Boolean? = null,

    @SerializedName("bus")
    val bus: kotlin.Boolean? = null,

    @SerializedName("bicycle")
    val bicycle: kotlin.Boolean? = null

)

