/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models


import com.google.gson.annotations.SerializedName

/**
 * Class of road (ranked in descending order)
 *
 * Values: motorway,trunk,primary,secondary,tertiary,unclassified,residential,service_other
 */

enum class RoadClass(val value: kotlin.String) {

    @SerializedName(value = "motorway")
    motorway("motorway"),

    @SerializedName(value = "trunk")
    trunk("trunk"),

    @SerializedName(value = "primary")
    primary("primary"),

    @SerializedName(value = "secondary")
    secondary("secondary"),

    @SerializedName(value = "tertiary")
    tertiary("tertiary"),

    @SerializedName(value = "unclassified")
    unclassified("unclassified"),

    @SerializedName(value = "residential")
    residential("residential"),

    @SerializedName(value = "service_other")
    service_other("service_other");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is RoadClass) "$data" else null

        /**
         * Returns a valid [RoadClass] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): RoadClass? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

