/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param trip 
 * @param id An identifier to disambiguate requests (echoed by the server).
 */


data class RouteResponse (

    @SerializedName("trip")
    val trip: RouteResponseTrip,

    /* An identifier to disambiguate requests (echoed by the server). */
    @SerializedName("id")
    val id: kotlin.String? = null

)

