/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param locations
 * @param costing
 * @param id An identifier to disambiguate requests (echoed by the server).
 * @param costingOptions
 * @param avoidLocations
 * @param avoidPolygons One or multiple exterior rings of polygons in the form of nested JSON arrays. Roads intersecting these rings will be avoided during path finding. Open rings will be closed automatically.
 * @param directionsOptions
 */

data class RouteRequest(

    @SerializedName("locations")
    val locations: List<RoutingWaypoint>,

    @SerializedName("costing")
    val costing: CostingModel,

    /* An identifier to disambiguate requests (echoed by the server). */
    @SerializedName("id")
    var id: kotlin.String = "route",

    @SerializedName("costing_options")
    val costingOptions: CostingOptions? = null,

    @SerializedName("avoid_locations")
    val avoidLocations: List<RoutingWaypoint>? = null,

    /* One or multiple exterior rings of polygons in the form of nested JSON arrays. Roads intersecting these rings will be avoided during path finding. Open rings will be closed automatically. */
    @SerializedName("avoid_polygons")
    val avoidPolygons: List<List<List<Double>>>? = null,

    @SerializedName("directions_options")
    val directionsOptions: DirectionsOptions? = null,

    @SerializedName("banner_instructions")
    val bannerInstructions: Boolean = true,

    @SerializedName("voice_instructions")
    val voiceInstructions: Boolean = true,

    @SerializedName("language")
    val language: ValhallaLanguages = ValhallaLanguages.enMinusUS
)

