/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param maneuvers 
 * @param shape An encoded polyline (https://developers.google.com/maps/documentation/utilities/polylinealgorithm) with 6 digits of decimal precision.
 * @param summary 
 */


data class RouteLeg (

    @SerializedName("maneuvers")
    val maneuvers: kotlin.collections.List<RouteManeuver>,

    /* An encoded polyline (https://developers.google.com/maps/documentation/utilities/polylinealgorithm) with 6 digits of decimal precision. */
    @SerializedName("shape")
    val shape: kotlin.String,

    @SerializedName("summary")
    val summary: RouteSummary

)

