/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param excludeTunnel Excludes roads marked as tunnels
 * @param excludeBridge Excludes roads marked as bridges
 * @param excludeRamp Excludes roads marked as ramps
 * @param excludeClosures Excludes roads marked as closed
 * @param minRoadClass The lowest road class allowed
 * @param maxRoadClass The highest road class allowed
 */


data class RoutingWaypointAllOfSearchFilter (

    /* Excludes roads marked as tunnels */
    @SerializedName("exclude_tunnel")
    val excludeTunnel: kotlin.Boolean? = false,

    /* Excludes roads marked as bridges */
    @SerializedName("exclude_bridge")
    val excludeBridge: kotlin.Boolean? = false,

    /* Excludes roads marked as ramps */
    @SerializedName("exclude_ramp")
    val excludeRamp: kotlin.Boolean? = false,

    /* Excludes roads marked as closed */
    @SerializedName("exclude_closures")
    val excludeClosures: kotlin.Boolean? = true,

    /* The lowest road class allowed */
    @SerializedName("min_road_class")
    val minRoadClass: RoadClass? = null,

    /* The highest road class allowed */
    @SerializedName("max_road_class")
    val maxRoadClass: RoadClass? = null

)

