/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param status The response status code
 * @param statusMessage The response status message
 * @param units 
 * @param language 
 * @param locations 
 * @param legs 
 * @param summary 
 */


data class RouteResponseTrip (

    /* The response status code */
    @SerializedName("status")
    val status: kotlin.Int,

    /* The response status message */
    @SerializedName("status_message")
    val statusMessage: kotlin.String,

    @SerializedName("units")
    val units: ValhallaLongUnits = ValhallaLongUnits.kilometers,

    @SerializedName("language")
    val language: ValhallaLanguages = ValhallaLanguages.enMinusUS,

    @SerializedName("locations")
    val locations: kotlin.collections.List<RoutingResponseWaypoint>,

    @SerializedName("legs")
    val legs: kotlin.collections.List<RouteLeg>,

    @SerializedName("summary")
    val summary: RouteSummary

)

