/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param time The estimated travel time, in seconds
 * @param length The estimated travel distance, in `units` (km or mi)
 * @param minLat The minimum latitude of the bounding box containing the route.
 * @param maxLat The maximum latitude of the bounding box containing the route.
 * @param minLon The minimum longitude of the bounding box containing the route.
 * @param maxLon The maximum longitude of the bounding box containing the route.
 */


data class RouteSummary (

    /* The estimated travel time, in seconds */
    @SerializedName("time")
    val time: kotlin.Double,

    /* The estimated travel distance, in `units` (km or mi) */
    @SerializedName("length")
    val length: kotlin.Double,

    /* The minimum latitude of the bounding box containing the route. */
    @SerializedName("min_lat")
    val minLat: kotlin.Double,

    /* The maximum latitude of the bounding box containing the route. */
    @SerializedName("max_lat")
    val maxLat: kotlin.Double,

    /* The minimum longitude of the bounding box containing the route. */
    @SerializedName("min_lon")
    val minLon: kotlin.Double,

    /* The maximum longitude of the bounding box containing the route. */
    @SerializedName("max_lon")
    val maxLon: kotlin.Double

)

