/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param lat The latitude of a point in the shape.
 * @param lon The longitude of a point in the shape.
 * @param type A `break` represents the start or end of a leg, and allows reversals. A `through` location is an intermediate waypoint that must be visited between `break`s, but at which reversals are not allowed. A `via` is similar to a `through` except that reversals are allowed. A `break_through` is similar to a `break` in that it can be the start/end of a leg, but does not allow reversals.
 */


data class SimpleRoutingWaypoint (

    /* The latitude of a point in the shape. */
    @SerializedName("lat")
    val lat: kotlin.Double,

    /* The longitude of a point in the shape. */
    @SerializedName("lon")
    val lon: kotlin.Double,

    /* A `break` represents the start or end of a leg, and allows reversals. A `through` location is an intermediate waypoint that must be visited between `break`s, but at which reversals are not allowed. A `via` is similar to a `through` except that reversals are allowed. A `break_through` is similar to a `break` in that it can be the start/end of a leg, but does not allow reversals. */
    @SerializedName("type")
    val type: Type? = Type.`break`

) {

    /**
     * A `break` represents the start or end of a leg, and allows reversals. A `through` location is an intermediate waypoint that must be visited between `break`s, but at which reversals are not allowed. A `via` is similar to a `through` except that reversals are allowed. A `break_through` is similar to a `break` in that it can be the start/end of a leg, but does not allow reversals.
     *
     * Values: `break`,through,via,break_through
     */
    enum class Type(val value: kotlin.String) {
        @SerializedName(value = "break") `break`("break"),
        @SerializedName(value = "through") through("through"),
        @SerializedName(value = "via") via("via"),
        @SerializedName(value = "break_through") break_through("break_through");
    }
}

