/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models


import com.google.gson.annotations.SerializedName

/**
 * An object containing a numeric value and its formatted text representation.
 *
 * @param text String value.
 * @param `value` Numeric value.
 */


data class TextValueObject (

    /* String value. */
    @SerializedName("text")
    val text: kotlin.String,

    /* Numeric value. */
    @SerializedName("value")
    val `value`: java.math.BigDecimal

)

