/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param attributes 
 * @param action Determines whether the list of attributes will be used as a whitelist or a blacklist.
 */


data class TraceAttributeFilterOptions (

    @SerializedName("attributes")
    val attributes: kotlin.collections.List<TraceAttributeKey>,

    /* Determines whether the list of attributes will be used as a whitelist or a blacklist. */
    @SerializedName("action")
    val action: Action

) {

    /**
     * Determines whether the list of attributes will be used as a whitelist or a blacklist.
     *
     * Values: include,exclude
     */
    enum class Action(val value: kotlin.String) {
        @SerializedName(value = "include") include("include"),
        @SerializedName(value = "exclude") exclude("exclude");
    }
}

