/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.mapapplication.originCode.net.models


import com.google.gson.annotations.SerializedName

/**
 * Attributes used to describe a WiFi access point.
 *
 * @param macAddress The MAC address of the WiFi node. It's typically called a BSS, BSSID or MAC address. Separators must be `:` (colon).
 * @param signalStrength The current signal strength measured in dBm.
 * @param signalToNoiseRatio The current signal to noise ratio measured in dB.
 * @param age The number of milliseconds since this access point was detected.
 * @param channel The channel over which the client is communication with the access point.
 */


data class WiFiAccessPoint (

    /* The MAC address of the WiFi node. It's typically called a BSS, BSSID or MAC address. Separators must be `:` (colon). */
    @SerializedName("macAddress")
    val macAddress: kotlin.String,

    /* The current signal strength measured in dBm. */
    @SerializedName("signalStrength")
    val signalStrength: kotlin.Int? = null,

    /* The current signal to noise ratio measured in dB. */
    @SerializedName("signalToNoiseRatio")
    val signalToNoiseRatio: kotlin.Int? = null,

    /* The number of milliseconds since this access point was detected. */
    @SerializedName("age")
    val age: kotlin.Int? = null,

    /* The channel over which the client is communication with the access point. */
    @SerializedName("channel")
    val channel: kotlin.Int? = null

)

